//
// Created by user on 4/19/24.
//

#ifndef OTUS_CPP_BASIC_2024_03_USOLTSEVPETR_CHECK_VALUE_H
#define OTUS_CPP_BASIC_2024_03_USOLTSEVPETR_CHECK_VALUE_H

int get_check(const int target_value);

#endif //OTUS_CPP_BASIC_2024_03_USOLTSEVPETR_CHECK_VALUE_H
